### ISSUE TITLE
Provide easier way to test local changes made to already published plugin

### ISSUE THREAD

**Issue by endeepak** [ekstep/EkStep-Content-SDK#2]
If a plugin is published on portal and if you have local changes to plugin and serve it via SDK, the local changes are not picked up. This makes it hard to test changes to existing plugins. Please provide easier way to test changes

**Comment by steotia** [comment]
cc @SanthoshVasabhaktula 

I spoke to Santhosh earlier and we decided to change the load order so that local plugins will override published plugins.

This is critical because there is no workaround. Requesting an early fix.

**Comment by SanthoshVasabhaktula** [comment]
This is completed and deployed on dev.
