### ISSUE TITLE
Data used for scaffolding should be text files instead of binary zip file

### ISSUE THREAD

**Issue by endeepak** [ekstep/EkStep-Content-SDK#3]
[Data](https://github.com/ekstep/EkStep-Content-SDK/tree/master/data) used for scaffolding should be text files instead of binary zip file. This would help in viewing the files used in scaffolding and tracking changes made to these over time

**Comment by SanthoshVasabhaktula** [comment]
@endeepak - That is completely internal to the sdk team. However once a plugin is created using the sdk - you can view the text files. I do not understand why would someone view the files used in scaffolding?

@cksachdev

**Comment by endeepak** [comment]
@SanthoshVasabhaktula If some one wants contribute changes to these files. It easier to track and review changes if these are text files. This is more from usability point of view for developers and contributors. Is there a reason for having additional steps of zip and unzip of these files?

**Comment by endeepak** [comment]
Adding more context on contributions : In near future we would be adding ability to scaffold a plugin with test framework (jasmine), test runner(karma) setup. This becomes more important when we open this to the public 
cc: @sferoz @steotia @surendrasinghs
