### ISSUE TITLE
 Plugin created with hyphen in plugin name does not load

### ISSUE THREAD

**Issue by endeepak** [ekstep/EkStep-Content-SDK#5]
Steps to reproduce:

1. Create plugin with hyphen in name and serve it using SDK
![image](https://cloud.githubusercontent.com/assets/310608/24156213/01e8e832-0e7c-11e7-853c-208559a64272.png)

2. Add the new plugin from using developer mode in editor

**Actual Result:**
Plugin fails to load and following errors is seen on console

![image](https://cloud.githubusercontent.com/assets/310608/24156416/76afdb4e-0e7c-11e7-8d67-5f0e3236990e.png)

**Comment by SanthoshVasabhaktula** [comment]
Issue moved to [ekstep/Content-Editor #261](https://github.com/ekstep/Content-Editor/issues/261) via [**ZenHub**](https://www.zenhub.com/)
