### ISSUE TITLE
EkstepEditorAPI.getPluginRepo() always returns dev.ekstep.in

### ISSUE THREAD

**Issue by DaipayanRoy** [ekstep/EkStep-Content-SDK#6]
We are trying to create a new plugin which requires us to create a wizard. In order for the wizard to load we are giving a path as such 

controllerPath = EkstepEditorAPI.getPluginRepo() + '/org.ekstep.literacy.wordpicker-1.0/editor/wordpickerapp.js'

In here the EkstepEditorAPI.getPluginRepo() always returns dev.ekstep.in, as a result the plugin does not work on the dev environment and in order for it to run have to hard code 'https://localhost:8081'.

Ideally "EkstepEditorAPI.getPluginRepo()" should return "https://localhost:8081" for local plugins.

**Comment by SanthoshVasabhaktula** [comment]
@DaipayanRoy - That is an incorrect way to resolve the resource.

Use the following:
```
controllerPath = EkstepEditorAPI.resolvePluginResource(this.manifest.id, this.manifest.ver, "editor/wordpickerapp.js");
```

@endeepak - Please ensure that none of the plugin developers use `EkstepEditorAPI.getPluginRepo()` function call in their respective plugins

@surendrasinghs @cksachdev

**Comment by endeepak** [comment]
Thanks @SanthoshVasabhaktula. Could you please update the wiki / docs if this is not mentioned anywhere

@DaipayanRoy Can you please test this and confirm

**Comment by SanthoshVasabhaktula** [comment]
@endeepak - That is updated as part of the JSDocs and the function itself is deprecated. I will send out list of deprecated variables and functions that needs to be changed and also create issues in Contributed-Plugins repo to fix the same.
