### ISSUE TITLE
Blocker for Funtoot when consuming the SDK

### ISSUE THREAD

**Issue by steotia** [ekstep/EkStep-Content-SDK#7]
I debugged the issue related to loading of Numerals counting plugin in SDK, and I think the issue is related to timing
The dependencies are loaded first, and because the dependencies type is "js", they get injected into the <script> tag, but the plugin code is getting evaluated before those scripts are loaded in editor
Can you please help get more information on how this can be fixed?
 
I’ll start a conversation on the Slack channel.
 
Regards,
Ram

**Comment by steotia** [comment]
cc @cksachdev @SanthoshVasabhaktula @sferoz

**Comment by SanthoshVasabhaktula** [comment]
Issue moved to [ekstep/Content-Editor #267](https://github.com/ekstep/Content-Editor/issues/267) via [**ZenHub**](https://www.zenhub.com/)
